---
title: "Music Library Dataset Preparation"
output: html_notebook
---

```{r message = FALSE}
# import required libaries
require(dplyr)
require(tuneR)
require(seewave)
require(doParallel)
set.seed(12481)
```

```{r}
# import the metadata information
music <- data.table::fread("C:/Users/Jake/Desktop/selected_music.csv")
```

Splitting the MFCC descriptors calculation into four parts to work within memory limitations.

```{r}
# start a parallel processing cluster
cl <- makeCluster(3, type = "SOCK")
registerDoParallel(cl)

## Calculate MFCC descriptors - rows 1:700
MFCC_descriptors.1 <- foreach (row = 1:700, .combine = rbind, .packages = c("tuneR", "seewave")) %dopar% {
  # declare a vector to hold the descriptors
  descriptors <- rep(NA, 35930)
  names(descriptors) <- c("song", "genre",
        outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), 
              c("start", "mid", "end"), FUN = paste, sep = "."))
    
    # store the song title - album - artist
    # replace commas, colons, and semicolons with underscores to avoid interferring with reading the csv
    descriptors$song <- paste(music[row, "Title"], music[row, "Album"], music[row, "Artist"], sep = " - ")
    descriptors$song <- gsub(",", "_", descriptors$song)
    descriptors$song <- gsub(";", "_", descriptors$song)
    descriptors$song <- gsub(":", "_", descriptors$song)
    
    # store the genre
    descriptors$genre <- music[row, "Genre"]
    
    # load the wave
    # using mp3 function if mp3
    if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "3") {
      wave.file <- readMP3(paste(music[row, "Path"], music[row, "Filename"], sep = "")) 
    }
    # using flac function if flac
    else if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "c") {
      # convert flac to wave
      wav2flac(paste(music[row, "Path"], music[row, "Filename"], sep = ""), reverse = TRUE, path2exe = "C:/Users/Jake/Desktop/")
      
      # load wave, then delete the saved wave file
      wave.file <- readWave(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
      file.remove(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
    }
    
  # strip silence
  wave.file <- noSilence(wave.file)
  
  # cut three 10 s segments from the wave file centered on approximate quarter points
  cut.points <- floor(c(1, 2, 3) * 0.25 * length(wave.file))
  segments <- cbind(cut.points - 5*wave.file@samp.rate, cut.points + 5*wave.file@samp.rate)
  
  wave.start <- wave.file[segments[1, 1] : segments [1, 2]]
  wave.mid <- wave.file[segments[2, 1] : segments [2, 2]]
  wave.end <- wave.file[segments[3, 1] : segments [3, 2]]
  
  # calculate MFCC descriptors
  # vectorizing the results put them in the appropriate order for the dataframe
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "start", FUN = paste, sep = ".")] <- c(melfcc(wave.start))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "mid", FUN = paste, sep = ".")] <- c(melfcc(wave.mid))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "end", FUN = paste, sep = ".")] <- c(melfcc(wave.end))
  
  return(descriptors)
}

# save the calculated descriptors
save(MFCC_descriptors.1, file = "MFCC_descriptors_part1")

# remove R table from memory 
rm(MFCC_descriptors.1)



## Calculate MFCC descriptors - rows 701:1400
MFCC_descriptors.2 <- foreach (row = 701:1400, .combine = rbind, .packages = c("tuneR", "seewave")) %dopar% {
  # declare a vector to hold the descriptors
  descriptors <- rep(NA, 35930)
  names(descriptors) <- c("song", "genre",
        outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), 
              c("start", "mid", "end"), FUN = paste, sep = "."))
    
    # store the song title - album - artist
    # replace commas, colons, and semicolons with underscores to avoid interferring with reading the csv
    descriptors$song <- paste(music[row, "Title"], music[row, "Album"], music[row, "Artist"], sep = " - ")
    descriptors$song <- gsub(",", "_", descriptors$song)
    descriptors$song <- gsub(";", "_", descriptors$song)
    descriptors$song <- gsub(":", "_", descriptors$song)
    
    # store the genre
    descriptors$genre <- music[row, "Genre"]
    
    # load the wave
    # using mp3 function if mp3
    if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "3") {
      wave.file <- readMP3(paste(music[row, "Path"], music[row, "Filename"], sep = "")) 
    }
    # using flac function if flac
    else if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "c") {
      # convert flac to wave
      wav2flac(paste(music[row, "Path"], music[row, "Filename"], sep = ""), reverse = TRUE, path2exe = "C:/Users/Jake/Desktop/")
      
      # load wave, then delete the saved wave file
      wave.file <- readWave(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
      file.remove(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
    }
    
  # strip silence
  wave.file <- noSilence(wave.file)
  
  # cut three 10 s segments from the wave file centered on approximate quarter points
  cut.points <- floor(c(1, 2, 3) * 0.25 * length(wave.file))
  segments <- cbind(cut.points - 5*wave.file@samp.rate, cut.points + 5*wave.file@samp.rate)
  
  wave.start <- wave.file[segments[1, 1] : segments [1, 2]]
  wave.mid <- wave.file[segments[2, 1] : segments [2, 2]]
  wave.end <- wave.file[segments[3, 1] : segments [3, 2]]
  
  # calculate MFCC descriptors
  # vectorizing the results put them in the appropriate order for the dataframe
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "start", FUN = paste, sep = ".")] <- c(melfcc(wave.start))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "mid", FUN = paste, sep = ".")] <- c(melfcc(wave.mid))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "end", FUN = paste, sep = ".")] <- c(melfcc(wave.end))
  
  return(descriptors)
}

# save the calculated descriptors
save(MFCC_descriptors.2, file = "MFCC_descriptors_part2")

# remove R table from memory 
rm(MFCC_descriptors.2)



## Calculate MFCC descriptors - rows 1401-2100
MFCC_descriptors.3 <- foreach (row = 1401:2100, .combine = rbind, .packages = c("tuneR", "seewave")) %dopar% {
  # declare a vector to hold the descriptors
  descriptors <- rep(NA, 35930)
  names(descriptors) <- c("song", "genre",
        outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), 
              c("start", "mid", "end"), FUN = paste, sep = "."))
    
    # store the song title - album - artist
    # replace commas, colons, and semicolons with underscores to avoid interferring with reading the csv
    descriptors$song <- paste(music[row, "Title"], music[row, "Album"], music[row, "Artist"], sep = " - ")
    descriptors$song <- gsub(",", "_", descriptors$song)
    descriptors$song <- gsub(";", "_", descriptors$song)
    descriptors$song <- gsub(":", "_", descriptors$song)
    
    # store the genre
    descriptors$genre <- music[row, "Genre"]
    
    # load the wave
    # using mp3 function if mp3
    if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "3") {
      wave.file <- readMP3(paste(music[row, "Path"], music[row, "Filename"], sep = "")) 
    }
    # using flac function if flac
    else if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "c") {
      # convert flac to wave
      wav2flac(paste(music[row, "Path"], music[row, "Filename"], sep = ""), reverse = TRUE, path2exe = "C:/Users/Jake/Desktop/")
      
      # load wave, then delete the saved wave file
      wave.file <- readWave(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
      file.remove(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
    }
    
  # strip silence
  wave.file <- noSilence(wave.file)
  
  # cut three 10 s segments from the wave file centered on approximate quarter points
  cut.points <- floor(c(1, 2, 3) * 0.25 * length(wave.file))
  segments <- cbind(cut.points - 5*wave.file@samp.rate, cut.points + 5*wave.file@samp.rate)
  
  wave.start <- wave.file[segments[1, 1] : segments [1, 2]]
  wave.mid <- wave.file[segments[2, 1] : segments [2, 2]]
  wave.end <- wave.file[segments[3, 1] : segments [3, 2]]
  
  # calculate MFCC descriptors
  # vectorizing the results put them in the appropriate order for the dataframe
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "start", FUN = paste, sep = ".")] <- c(melfcc(wave.start))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "mid", FUN = paste, sep = ".")] <- c(melfcc(wave.mid))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "end", FUN = paste, sep = ".")] <- c(melfcc(wave.end))
  
  return(descriptors)
}

# save the calculated descriptors
save(MFCC_descriptors.3, file = "MFCC_descriptors_part3")

# remove R table from memory
rm(MFCC_descriptors.3)



## Calculate MFCC descriptors - rows 2101-2800
MFCC_descriptors.4 <- foreach (row = 2101:2800, .combine = rbind, .packages = c("tuneR", "seewave")) %dopar% {
  # declare a vector to hold the descriptors
  descriptors <- rep(NA, 35930)
  names(descriptors) <- c("song", "genre",
        outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), 
              c("start", "mid", "end"), FUN = paste, sep = "."))
    
    # store the song title - album - artist
    # replace commas, colons, and semicolons with underscores to avoid interferring with reading the csv
    descriptors$song <- paste(music[row, "Title"], music[row, "Album"], music[row, "Artist"], sep = " - ")
    descriptors$song <- gsub(",", "_", descriptors$song)
    descriptors$song <- gsub(";", "_", descriptors$song)
    descriptors$song <- gsub(":", "_", descriptors$song)
    
    # store the genre
    descriptors$genre <- music[row, "Genre"]
    
    # load the wave
    # using mp3 function if mp3
    if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "3") {
      wave.file <- readMP3(paste(music[row, "Path"], music[row, "Filename"], sep = "")) 
    }
    # using flac function if flac
    else if (substr(music[row, "Filename"], nchar(music[row, "Filename"]), nchar(music[row, "Filename"])) == "c") {
      # convert flac to wave
      wav2flac(paste(music[row, "Path"], music[row, "Filename"], sep = ""), reverse = TRUE, path2exe = "C:/Users/Jake/Desktop/")
      
      # load wave, then delete the saved wave file
      wave.file <- readWave(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
      file.remove(paste(music[row, "Path"], sub("flac", "wav", music[row, "Filename"]), sep = ""))
    }
    
  # strip silence
  wave.file <- noSilence(wave.file)
  
  # cut three 10 s segments from the wave file centered on approximate quarter points
  cut.points <- floor(c(1, 2, 3) * 0.25 * length(wave.file))
  segments <- cbind(cut.points - 5*wave.file@samp.rate, cut.points + 5*wave.file@samp.rate)
  
  wave.start <- wave.file[segments[1, 1] : segments [1, 2]]
  wave.mid <- wave.file[segments[2, 1] : segments [2, 2]]
  wave.end <- wave.file[segments[3, 1] : segments [3, 2]]
  
  # calculate MFCC descriptors
  # vectorizing the results put them in the appropriate order for the dataframe
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "start", FUN = paste, sep = ".")] <- c(melfcc(wave.start))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "mid", FUN = paste, sep = ".")] <- c(melfcc(wave.mid))
  descriptors[outer(outer(outer("MFCC.V", 1:12, FUN = paste, sep = ""), 1:998, FUN = paste, sep = "."), "end", FUN = paste, sep = ".")] <- c(melfcc(wave.end))
  
  return(descriptors)
}

# save the calculated descriptors
save(MFCC_descriptors.4, file = "MFCC_descriptors_part4")

# remove R table from memory
rm(MFCC_descriptors.4)

# stop parallel processing cluster
stopCluster(cl)
```
