---
title: "Training Set Preparation"
author: "Jake Smith"
date: "7/8/2019"
---

```{r setup, include=FALSE}
set.seed(18341325)
require(dplyr)
require(tidyr)
require(ggplot2)
```

```{r}
# load the dataset
MFCC <- data.table::fread("~/Data/MFCC_descriptors_compiled.csv")

# set seed for reproducible train/test split
set.seed(998)

## using an 60/20/20 train/validation/test split stratified by genre
# divide out 20% of the dataset for the test set
MFCC.test <- MFCC %>% group_by(genre) %>% sample_n(0.2 * 200) %>% ungroup()
MFCC.train <- setdiff(MFCC, MFCC.test)

# divide out an additional 20% of the dataset for the validation set
MFCC.validation <- MFCC.train %>% group_by(genre) %>% sample_n(0.2 * 200) %>% ungroup()
MFCC.train <- setdiff(MFCC.train, MFCC.validation)

# remove unsplit MFCC dataset from memory
rm(MFCC)
```

```{r}
# there are a handful of cases that have caused an error in the descriptor calculator
# they do not appear clustered to a particular genre to the eye, so we will simply remove them
MFCC.train <- MFCC.train[complete.cases(MFCC.train), ]
MFCC.validation <- MFCC.validation[complete.cases(MFCC.validation), ]

# plot histograms of a subset of MFCC descriptors
ggplot(
  gather(select(MFCC.train, paste("MFCC.V", 1:12, ".500.", "start", sep = "")))
  ) + geom_histogram(aes(x = value)) + facet_wrap(~key)
```

```{r}
# plot histograms of a subset of MFCC descriptors
ggplot(
  gather(select(MFCC.train, paste("MFCC.V", 1:12, ".500.", "mid", sep = "")))
  ) + geom_histogram(aes(x = value)) + facet_wrap(~key)
```

```{r}
# plot histograms of a subset of MFCC descriptors
ggplot(
  gather(select(MFCC.train, paste("MFCC.V", 1:12, ".500.", "mid", sep = "")))
  ) + geom_histogram(aes(x = value)) + facet_wrap(~key)
```

```{r}
## the decriptors appear reasonably well normally distributed, so we will not transform them non-linearly
## we will scale the MFCC values to -1 to 1

# find the maximum absolute value of the train set
MFCC.max <- max(abs(select(MFCC.train, -song, -genre)))

# divide all MFCC values by the train set maximum
MFCC.train <- mutate_at(MFCC.train, vars(-song, - genre), function(x) {x / MFCC.max})
MFCC.validation <- mutate_at(MFCC.validation, vars(-song, - genre), function(x) {x / MFCC.max})
MFCC.test <- mutate_at(MFCC.test, vars(-song, - genre), function(x) {x / MFCC.max})
```

```{r}
## build X and Y matrices from the training and validation sets
# convert the features into a matrix
X.train <- as.matrix(select(MFCC.train, -song, -genre))
X.validation <- as.matrix(select(MFCC.validation, -song, -genre))

# one-hot encode the observed genres
Y.train <- MFCC.train$genre %>% as.factor() %>% as.numeric() %>% keras::to_categorical()
Y.validation <- MFCC.validation$genre %>% as.factor() %>% as.numeric() %>% keras::to_categorical()

# remove the original train and validation sets from memory
rm(MFCC.train, MFCC.validation)
```

